openapi: 3.0.3
info:
  version: 0.1.1
  title: Open Insurance Initiative Requirements API
  description: This page contains the documentation for the Open Insurance Initiative Requirements API.
  contact:
    name: Open Insurance Initiative
    email: openinsuranceinitiative@gmail.com
  license:
    name: MIT License
    url: https://spdx.org/licenses/MIT.html
servers:
  - url: /open-insurance/annuity/nb/rapi
paths:
  /carriers/{carrier}/cases/{case}/requirements:
    post:
      description: |
        Called when it is determined that an action is needed with regards to the issuance of a policy. 

        This corresponds with the `urn:open-insurance-initiative:annuity:new-business:requirement:created` event.
      operationId: createRequirement
      security:
        - PartnerOpenIdConnect:
            - OpenInsurance.Requirements
      parameters:
        - $ref: "#/components/parameters/Carrier"
        - $ref: "#/components/parameters/Case"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatedEvent"
      responses:
        201:
          description: Created
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /carriers/{carrier}/cases/{case}/requirements/{id}/satisfy:
    put:
      description: |
        Called when a requirement has been satisfied. 

        This corresponds with the `urn:open-insurance-initiative:annuity:new-business:requirement:satisfied` event.
      operationId: satisfyRequirement
      security:
        - PartnerOpenIdConnect:
            - OpenInsurance.Requirements
      parameters:
        - $ref: "#/components/parameters/Carrier"
        - $ref: "#/components/parameters/Case"
        - $ref: "#/components/parameters/Requirement"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SatisfiedEvent"
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
components:
  securitySchemes:
    PartnerOpenIdConnect:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
  parameters:
    Carrier:
      name: carrier
      in: path
      description: The unique identifier of the insurance company.
      required: true
      schema:
        $ref: "#/components/schemas/CarrierCode"
    Case:
      name: case
      in: path
      description: The carrier-issued case number associated with the issuance of a policy.
      required: true
      schema:
        $ref: "#/components/schemas/CaseNumber"
    Requirement:
      name: id
      in: path
      description: The unique identifier of the satisfied requirement.
      required: true
      schema:
        $ref: "#/components/schemas/RequirementId"
  schemas:
    CarrierCode:
      type: string
      description: A unique identifier of the insurance carrier.
      minLength: 4
      maxLength: 32
    CaseNumber:
      type: string
      description: The carrier-issued case number associated with the issuance of a policy.
      minLength: 1
      maxLength: 64
    RequirementId:
      type: string
      description: The unique identifier of a requirement.
      minLength: 1
      maxLength: 64
    CreatedEvent:
      description: Represents an action that is or was needed in regards to the issuance of a policy.
      type: object
      additionalProperties: false
      required:
        - id
        - description
        - created
      properties:
        id:
          $ref: "#/components/schemas/RequirementId"
        description:
          type: string
          description: A description of the Requirement.
          minLength: 1
        created:
          type: string
          format: date-time
          description: The moment the requirement was created.
    SatisfiedEvent:
      type: object
      additionalProperties: false
      required:
        - satisfied
      properties:
        satisfied:
          type: string
          format: date-time
          description: The moment the requirement was satisfied.
